name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Add this event
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main' # You can set a default branch if desired

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup signing configure
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc ;
        gpg -d --batch --passphrase="${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" release.keystore.asc > release.keystore ;
        echo "signingStoreLocation=../release.keystore" > signing.properties ;
        echo "signingStorePassword=KAReOruifAQnp18" >> signing.properties ;
        echo "signingKeyAlias=release" >> signing.properties ;
        echo "signingKeyPassword=KAReOruifAQnp18" >> signing.properties ;
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload APK To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: |
          app/build/outputs/apk/release/*
